import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { EnquiryForm, ScrollTopDock, SiteFooter, SiteHeader, WhatsAppDock } from "@/components/site-shell";
import { CollectionExplorer, CompareView, QuoteForm } from "@/components/interactive";
import { brand, collections, processSteps, services } from "@/data/brand";

const pages:Record<string,{eyebrow:string;title:string;intro:string}> = {
  about:{eyebrow:"Our approach",title:"Furniture is where architecture becomes personal.",intro:"Trioak Furniture Co. is an Indore-based furniture design and manufacturing studio for residential, commercial, office and modular spaces."},
  collections:{eyebrow:"Explore the range",title:"Distinct furniture for every part of life.",intro:"Browse furniture collections designed around proportion, purpose, material and the character of your space."},
  projects:{eyebrow:"Selected spaces",title:"A portfolio built one considered detail at a time.",intro:"Residential, commercial and custom furniture stories. Project information remains intentionally neutral until verified details are supplied."},
  services:{eyebrow:"What we do",title:"From first sketch to final installation.",intro:"A connected furniture service spanning consultation, space planning, selection, manufacturing and handover."},
  gallery:{eyebrow:"Visual journal",title:"Spaces, materials and moments of craft.",intro:"A curated edit of real interiors exploring furniture, materials, atmosphere and modern ways of living."},
  inspiration:{eyebrow:"The Trioak journal",title:"Ideas for living and working beautifully.",intro:"Furniture thinking, material combinations, planning guidance and considered ways to shape more personal interiors."},
  blog:{eyebrow:"Design journal",title:"Ideas, materials and more considered spaces.",intro:"Original editorial topics prepared for future Trioak articles, project notes and furniture guidance."},
  contact:{eyebrow:"Begin a conversation",title:"Tell us about your space.",intro:"Share your brief, visit the Indore studio or begin directly on WhatsApp."},
  quote:{eyebrow:"Request a quotation",title:"Give your project a thoughtful beginning.",intro:"Share the essentials of your space and continue securely with Trioak on WhatsApp."},
  compare:{eyebrow:"Furniture comparison",title:"Compare directions for your space.",intro:"Review up to three saved collections before starting a consultation."},
  search:{eyebrow:"Search Trioak",title:"Find a direction for your space.",intro:"Search furniture collections by room, purpose or category."},
  catalogue:{eyebrow:"Catalogue",title:"A curated collection, coming together.",intro:"The downloadable Trioak catalogue can be added here when the approved PDF is supplied."},
  "privacy-policy":{eyebrow:"Legal",title:"Privacy policy",intro:"This placeholder policy must be reviewed and approved before handling production form submissions or analytics data."},
  terms:{eyebrow:"Legal",title:"Terms of use",intro:"This placeholder terms page must be reviewed and approved before public commercial use."},
};
const readableSlug=(value:string)=>value.split("-").map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(" ");
export function generateStaticParams(){
  const topLevel=Object.keys(pages).map((key)=>({slug:[key]}));
  const collectionPages=collections.map((item)=>({slug:["collections",item.slug]}));
  const projectPages=["contemporary-residence","executive-workspace","bespoke-bedroom-suite"].map((item)=>({slug:["projects",item]}));
  return [...topLevel,...collectionPages,...projectPages];
}
export const dynamicParams=false;
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;return {title:slug[0]==="projects"&&slug[1]?readableSlug(slug[1]):collections.find(x=>x.slug===slug[1])?.title||pages[slug[0]]?.title||"Furniture"}}
export default async function ContentPage({params}:{params:Promise<{slug:string[]}>}){
  const {slug}=await params,key=slug[0],detail=slug[1];const collection=key==="collections"&&detail?collections.find(x=>x.slug===detail):null;const isProject=key==="projects"&&detail;
  const page=collection?{eyebrow:"Trioak collection",title:collection.title,intro:collection.description}:isProject?{eyebrow:"Selected project · Placeholder",title:readableSlug(detail),intro:"An editorial project study awaiting verified photography, location and final scope details."}:pages[key];if(!page)notFound();const hero="/media/hero/trioak-editorial-placeholder.png";
  const heroSource=key==="collections"?"/images/real/living-room.jpg":key==="gallery"?"/images/real/interior-detail.jpg":key==="about"?"/images/workshop/material-craft.png":key==="projects"||key==="services"?"/images/office/executive-office.png":key==="quote"||key==="contact"?"/images/bedroom/bespoke-bedroom.png":collection?.image||hero;
  const galleryImages=[["Sculpted living","/images/real/living-room.jpg"],["Quiet bedroom","/images/real/bedroom.jpg"],["Gathering table","/images/real/dining.jpg"],["Executive focus","/images/real/office.jpg"],["Architectural storage","/images/real/modular.jpg"],["Material mood","/images/real/interior-detail.jpg"],["Living details","/images/real/living-room.jpg"],["Dining atmosphere","/images/real/dining.jpg"]];
  return <><SiteHeader/><main id="main" className="innerMain"><section className={`innerHero innerHero-${key}`}><Image src={heroSource} alt="Trioak furniture editorial interior" fill priority sizes="100vw" unoptimized/><div className="heroShade"/><div><p className="eyebrow light">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.intro}</p></div></section>
  {key==="collections"&&!detail&&<CollectionExplorer/>}
  {key==="search"&&<CollectionExplorer/>}
  {key==="services"&&<section className="servicePage section">{services.map((x,i)=><article key={x.title}><span>0{i+1}</span><h2>{x.title}</h2><p>{x.description}</p><Link href="/contact">Discuss this service →</Link></article>)}</section>}
  {key==="projects"&&!detail&&<section className="projectListing section">{[["Contemporary Residence",hero],["Executive Workspace","/images/office/executive-office.png"],["Bespoke Bedroom Suite","/images/bedroom/bespoke-bedroom.png"]].map(([x,image],i)=><Link key={x} href={`/projects/${x.toLowerCase().replaceAll(" ","-")}`}><div style={{backgroundImage:`linear-gradient(rgba(16,16,15,.${i+1}),rgba(16,16,15,.3)),url(${image})`}}/><p>Editorial placeholder · Details to be verified</p><h2>{x}</h2><span>View project ↗</span></Link>)}</section>}
  {(collection||isProject||key==="about")&&<><section className="editorial section"><div><p className="eyebrow">How we work</p><h2>Considered from every angle.</h2></div><div><p>Every brief begins with the space: its dimensions, light, movement and the people who use it. Materials, proportions and finishes are then resolved as one coherent idea.</p><p>This page is ready for approved Trioak photographs and verified project-specific details.</p></div></section><section className="process section"><p className="eyebrow">The journey</p><ol className="timeline">{processSteps.map((x,i)=><li key={x}><span>0{i+1}</span><p>{x}</p></li>)}</ol></section></>}
  {key==="gallery"&&<section className="galleryExperience section"><div className="galleryIntro"><div className="galleryIntroArt"><p className="eyebrow">The visual edit</p><div className="materialOrbit" aria-hidden="true"><i/><i/><i/><span className="orbitPhoto orbitPhotoOne"/><span className="orbitPhoto orbitPhotoTwo"/><b>01<small>/08</small></b></div><p className="orbitNote">Spaces · Materials · Atmosphere</p></div><div className="galleryIntroCopy"><h2>Rooms with<br/><em>character.</em></h2><p>Real interiors selected to express Trioak&apos;s direction across living, dining, bedroom, workspace and custom furniture.</p></div></div><div className="galleryGrid">{galleryImages.map(([label,image],i)=><figure key={`${label}-${i}`} className="galleryItem"><div style={{backgroundImage:`linear-gradient(rgba(20,15,10,.${i%3+1}),rgba(20,15,10,.12)),url(${image})`}}/><figcaption><span>{String(i+1).padStart(2,"0")}</span>{label}<b>↗</b></figcaption></figure>)}</div></section>}
  {key==="inspiration"&&<section className="articles section">{["How to plan furniture around movement","A guide to warm wood tones","Building a calmer bedroom","The modern executive workspace","Material combinations with quiet impact","Making compact spaces work harder"].map((x,i)=><article key={x}><span>0{i+1} · Inspiration</span><h2>{x}</h2><p>Editorial content framework ready for Trioak’s approved guidance and project imagery.</p><a href={brand.whatsappUrl}>Ask Trioak ↗</a></article>)}</section>}
  {key==="contact"&&<section className="contactGrid section"><div><p className="eyebrow">Visit the studio</p><h2>In Indore,<br/>close to your project.</h2><address>{brand.address}</address><a href={brand.phoneHref}>{brand.phone}</a><a href={brand.alternatePhoneHref}>{brand.alternatePhone}</a><a href={`mailto:${brand.email}`}>{brand.email}</a><a className="textLink" href={brand.directions}>Get directions ↗</a></div><EnquiryForm/></section>}
  {key==="quote"&&<section className="quoteSection section"><div><p className="eyebrow">Project brief</p><h2>Start with the essentials.</h2><p>No instant estimates or invented pricing. Your information opens a pre-filled WhatsApp message so Trioak can respond personally.</p></div><QuoteForm/></section>}
  {key==="compare"&&<CompareView/>}
  {key==="blog"&&<section className="articles section">{["Choosing the right wood tone","Planning furniture around movement","A calmer approach to bedroom storage","What makes an executive workspace work","How material samples change a decision","Furniture care for Indian seasons"].map((x,i)=><article key={x}><span>0{i+1} · Editorial placeholder</span><h2>{x}</h2><p>Article framework ready for original, approved Trioak editorial content.</p><Link href="/contact">Ask Trioak ↗</Link></article>)}</section>}
  {["privacy-policy","terms","catalogue"].includes(key)&&<section className="legal section"><h2>Important note</h2><p>{page.intro}</p><p>Contact Trioak Furniture Co. directly for current information.</p></section>}
  <section className="pageCta"><p className="eyebrow light">Your space, considered</p><h2>Ready to start a conversation?</h2><a className="button lightButton" href={brand.whatsappUrl}>Enquire on WhatsApp ↗</a></section></main><SiteFooter/><ScrollTopDock/><WhatsAppDock/></>
}
